import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from "antd";
import tokens from "./tokens/tokens.json";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/options";
import { NextAuthProvider } from "@/providers/NextAuthProvider";
import LayoutProvider from "@/providers/LayoutProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await getServerSession(authOptions);
    return (
        <html lang="en">
            <body className={inter.className}>
                <ConfigProvider
                    theme={{
                        token: tokens.token,
                    }}
                >
                    <AntdRegistry>
                        <NextAuthProvider session={session}>
                            <LayoutProvider>{children}</LayoutProvider>
                        </NextAuthProvider>
                    </AntdRegistry>
                </ConfigProvider>
            </body>
        </html>
    );
}
